# Here we are using a local persistent volume:
# A local persistent volume represents a local disk directly-attached to a single 
# Kubernetes Node. (Using this just for test purposes).
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Mounting this folder on the host.
    path: "/mnt/data"

# *** This is an example of Azure config.
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins
#   #annotations: 
#    #pv.beta.kubernetes.io/gid: "1000"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   azureFile:
#     secretName: storage-connection
#     secretNamespace: jenkins
#     shareName: {{ .Values.jenkins.azurefileshare }}
#     readOnly: false
#   claimRef:
#     name: jenkins-pvc
#     kind: PersistenVolumeClaim
#     namespace: jenkins
#   persistentVolumeReclaimPolicy: Retain